#---------------------------------------------------------------------
# Manifest File to create Single Container Pod Deployment with Service
#
# Copyleft (c) by Denis Astahov 2020
#---------------------------------------------------------------------

---
apiVersion: v1
kind: Service
metadata:
  name: my-single-pod-service
  labels:
    env  : prod
    owner: DenisAstahov
  annotations:
    external-dns.alpha.kubernetes.io/hostname: your-login.soft-infra.geoscan.ru
    external-dns.alpha.kubernetes.io/ttl: 3600
spec:
  selector:
    project: cia    # Selecting PODS with those Labels
  ports:
    - name      : app-listener
      protocol  : TCP
      port      : 80  # Port on Load Balancer
      targetPort: 80  # Port on POD
      nodePort  : 30110
  type: LoadBalancer
